
import { TicketData } from "./tickets";

export const RICH_MOCK_TICKETS: TicketData[] = [
    {
        id: "1",
        code: "TCK-0142",
        status: "New",
        title: "Login failure on main dashboard after update",
        description: "User cannot access the dashboard after the recent v2.3 deployment. Getting 403 Forbidden.",
        product: "Catatmak",
        source: "WhatsApp",
        priority: "High",
        prioritySetAt: "12 Feb 2026 · 09:00",
        responseDue: "12 Feb · 11:00",
        resolveDue: "12 Feb · 17:00",
        createdAt: "10 mins ago",
        customer: "Budi Santoso"
    },
    {
        id: "2",
        code: "TCK-0143",
        status: "In Progress",
        title: "Bill export returning 500 server error",
        description: "Exporting PDF for monthly bills fails when date range > 30 days.",
        product: "Orbit Billiard",
        source: "Website",
        priority: "High",
        prioritySetAt: "11 Feb 2026 · 14:20",
        responseDue: "11 Feb · 15:20",
        resolveDue: "12 Feb · 10:00",
        createdAt: "2 hrs ago",
        customer: "Dewi Lestari"
    },
    {
        id: "3",
        code: "TCK-0140",
        status: "Pending",
        title: "Feature request: Dark mode for mobile app",
        product: "Joki Informatika",
        source: "Email",
        priority: "Low",
        prioritySetAt: "10 Feb 2026 · 10:00",
        responseDue: "11 Feb · 10:00",
        resolveDue: "17 Feb · 10:00",
        createdAt: "1 day ago",
        customer: "Rian Hidayat"
    },
    {
        id: "4",
        code: "TCK-0138",
        status: "Overdue",
        title: "Payment gateway timeout on BCA Virtual Account",
        product: "Orbit Billiard",
        source: "WhatsApp",
        priority: "High",
        prioritySetAt: "08 Feb 2026 · 08:30",
        responseDue: "08 Feb · 10:30",
        resolveDue: "08 Feb · 12:30",
        createdAt: "2 days ago",
        customer: "Siti Aminah"
    },
    {
        id: "5",
        code: "TCK-0145",
        status: "New",
        title: "User cannot reset password via email link",
        product: "Catatmak",
        source: "Email",
        priority: "Medium",
        prioritySetAt: "12 Feb 2026 · 10:45",
        responseDue: "12 Feb · 14:45",
        resolveDue: "13 Feb · 10:45",
        createdAt: "30 mins ago",
        customer: "Eko Prasetyo"
    },
    {
        id: "6",
        code: "TCK-0135",
        status: "Done",
        title: "Integrate new inventory module",
        product: "Joki Informatika",
        source: "Website",
        priority: "Medium",
        prioritySetAt: "09 Feb 2026 · 09:00",
        responseDue: "09 Feb · 13:00",
        resolveDue: "10 Feb · 09:00",
        createdAt: "3 days ago",
        customer: "Fajar Nugraha"
    },
    {
        id: "7",
        code: "TCK-0130",
        status: "Closed",
        title: "Spam inquiry ticket regarding promo",
        product: "Catatmak",
        source: "Website",
        priority: "Low",
        prioritySetAt: "05 Feb 2026 · 11:00",
        responseDue: "-",
        resolveDue: "-",
        createdAt: "5 days ago",
        customer: "Anonymous"
    },
    {
        id: "8",
        code: "TCK-0146",
        status: "In Progress",
        title: "Sidebar navigation glitch on tablet view",
        product: "Catatmak",
        source: "WhatsApp",
        priority: "Medium",
        prioritySetAt: "12 Feb 2026 · 08:15",
        responseDue: "12 Feb · 11:15",
        resolveDue: "12 Feb · 20:15",
        createdAt: "1 hr ago",
        customer: "Indah Permata"
    },
];
